name: Sync Blender Source

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_PUSH }}

      - name: Add upstream Blender repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://projects.blender.org/blender/blender.git
          git fetch upstream main

      - name: Merge latest changes
        run: |
          git merge --strategy=recursive --strategy-option=theirs upstream/main || true

      - name: Push to GitHub
        run: |
          git push origin main
